# Generated by Django 4.0.4 on 2022-04-28 07:46

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name=django.contrib.auth.models.User)),
                ('Full_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('contact', models.IntegerField()),
                ('address', models.CharField(max_length=255)),
                ('Upload_Cv', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='jobseeker',
            old_name='contact',
            new_name='Phone_no',
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='Education_level',
            field=models.CharField(choices=[('C', 'Certificate'), ('D', 'Degree'), ('M', 'Masters')], max_length=2),
        ),
    ]
