# Generated by Django 4.0.4 on 2022-04-28 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_rename_contact_jobseeker_phone_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseeker',
            name='Phone_no',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='contact',
            field=models.CharField(max_length=255),
        ),
    ]
