# Generated by Django 3.2.10 on 2022-04-29 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_mpesapayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpesapayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
