# Generated by Django 3.2.10 on 2022-04-29 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_mpesapayment_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=255)),
                ('requirements', models.TextField()),
                ('jobtype', models.TextField(choices=[('P', 'Part-Time'), ('R', 'Remote'), ('F', 'Full-Time')], max_length=30)),
            ],
        ),
    ]
