# Generated by Django 3.2.10 on 2022-04-30 13:19

import cloudinary.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20220430_0559'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobseeker',
            old_name='salary_Expectation',
            new_name='salary',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='id',
        ),
        migrations.RemoveField(
            model_name='jobseeker',
            name='Education',
        ),
        migrations.RemoveField(
            model_name='jobseeker',
            name='Education_level',
        ),
        migrations.RemoveField(
            model_name='jobseeker',
            name='Phone_no',
        ),
        migrations.RemoveField(
            model_name='jobseeker',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='jobseeker',
            name='job_category',
        ),
        migrations.RemoveField(
            model_name='jobseeker',
            name='jobid',
        ),
        migrations.RemoveField(
            model_name='jobseeker',
            name='jobtype',
        ),
        migrations.RemoveField(
            model_name='jobseeker',
            name='professsion',
        ),
        migrations.RemoveField(
            model_name='jobseeker',
            name='profile_pic',
        ),
        migrations.RemoveField(
            model_name='jobseeker',
            name='reference',
        ),
        migrations.RemoveField(
            model_name='jobseeker',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='jobseeker',
            name='status',
        ),
        migrations.RemoveField(
            model_name='jobseeker',
            name='work',
        ),
        migrations.AddField(
            model_name='employer',
            name='user',
            field=models.OneToOneField(default=444, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='availability',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='contact',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='email',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='password',
            field=models.CharField(default=3444, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='phone_no',
            field=models.CharField(default=4455, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='profile_photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='user',
            field=models.OneToOneField(default=2222, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.employer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='employer',
            name='company_pic',
            field=cloudinary.models.CloudinaryField(default=3444, max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='mpesapayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=33444, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='Profile_image',
            field=cloudinary.models.CloudinaryField(default=4444, max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_employer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_jobseeker',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
