# Generated by Django 3.2.10 on 2022-05-02 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20220430_1319'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Full_name',
            new_name='bio',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Upload_Cv',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Profile_image',
            new_name='profile_image',
        ),
        migrations.AddField(
            model_name='profile',
            name='referees',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='resume',
            field=models.IntegerField(default=22),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='skills',
            field=models.CharField(default=333, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='work_experience',
            field=models.CharField(default=344, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employer',
            name='user',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='name',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='contact',
            field=models.IntegerField(),
        ),
    ]
