# Generated by Django 2.2 on 2022-05-04 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseeker',
            name='salary',
            field=models.IntegerField(blank=True),
        ),
    ]
